version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    working_dir: /code
    command: "flask run --cert=/certs/cert.pem --key=/certs/key.pem"
    volumes:
      - .:/code:rw
      - /etc/letsencrypt/live/compymedic.duckdns.org/:/code/certs/
  redis:
    image: redis:alpine3.18
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local