version: "3.4"
services:
  web:
    container_name: FLASK_OCR_COMPARE_SERVICE
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /code
    volumes:
      - .:/code:rw
    environment:
      - FLASK_DEBUG
      - TESTING
      - FLASK_RUN_HOST
      - REDIS_CACHE_TYPE
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    container_name: REDIS_CONTAINER
    tty: true
    image: redis:alpine3.18
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
