version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/code:rw
  redis:
    image: redis:alpine3.18
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
