version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    working_dir: /code
    command: "flask run --cert=/var/certs/cert1.pem --key=/var/certs/privkey1.pem"
    volumes:
      - .:/code:rw
      - /etc/letsencrypt/archive/compymedic.duckdns.org:/var/certs:ro
  redis:
    image: redis:alpine3.18
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
